### ISSUE TITLE
Changing the range of x-axis for seaborn plot

### ISSUE THREAD

**Issue by LienDNguyen** [LienDNguyen/calcium_imaging#6]
Instead of plotting for the entire 500 s, I only want to plot from 0 to 200 s to highlight the UTP response. Still haven't googled out the solution, strangely.

**Comment by DanielSchuette** [comment]
Which of the new files in `./code/` are you referring to? I can make that change if you want me to. Also, are you still interesting in me bundling the `rate-of-rise` code into a re-usable package?

**Comment by DanielSchuette** [comment]
![figure_recreated](https://user-images.githubusercontent.com/36865868/47522154-1ba00a00-d895-11e8-859c-16f32101e201.png)

I added the source code that I used to create this figure to `./snippets/`. Is this `x axis` what you want? I'll work on the `rate-of-rise` tomorrow!

**Comment by LienDNguyen** [comment]
Yep, that's exactly what I wanted. Thanks! And no rush for the rate of rise (do focus during your classes :)).

**Comment by LienDNguyen** [comment]
Actually, the following 2 lines also work:
plt.xlim(0, 150)
plt.show()

I initially tried 
sns.plt.xlim(0, 150)
sns.plt.show()

which resulted in an error message. Sometimes python works in mysterious ways...
