### ISSUE TITLE
Test `ca_img_analyzer` module

### ISSUE THREAD

**Issue by DanielSchuette** [LienDNguyen/calcium_imaging#7]
I just created a test module called `ca_img_analyzer` and uploaded it to a version of the online Python package repository [PyPI](https://test.pypi.org/project/ca-img-analyzer/). The code is on GitHub too (open an issue in [that repository](https://github.com/DanielSchuette/ca_img_analyzer) in case of any problems with certain functions).

It would be extremely helpful if you could try to download and use the package. It currently only has test functions, but as soon as those work for you, I can refactor the `rate-of-rise` code that I wrote previously and you can download it as part of this package.

The following strategy hopefully works for you:

1. open the `Anaconda` prompt (should be like `cmd` under Windows)

2. type in: `python3 -m pip install --index-url https://test.pypi.org/simple/ ca_img_analyzer` (you might have to use just `python` instead of `python3`)

3. Now, you should be able to use the package from within a `jupyter notebook`:

```python
import ca_img_analyzer.rof as rof
import ca_img_analyzer.auc as auc

rof.greetings()
auc.greetings()
```

4. This should print:

```
rof
auc
```

**Comment by DanielSchuette** [comment]
Another update: I added an `auc` function. The example [here](https://github.com/DanielSchuette/ca_img_analyzer) show how to use it. Just replace items 3. and 4. above with the new example code. Hope it works!

**Comment by DanielSchuette** [comment]
I just implemented the `rate-of-rise` [algorithm](https://github.com/DanielSchuette/ca_img_analyzer/blob/master/ca_img_analyzer/rate_of_rise.py) as part of the module I created. It is not in the PyPI repository just yet, only here on GitHub. But if you could send me an example data set (just the regular format that you get after using the command line tool for normalizing the data/subtracting the background) via email, I can verify that the algorithm works and that it gives the expected results. If that is the case (I probably have to debug a bunch of things though), I will upload all the code and an example for the `rate-of-rise` calculation. In the end, you hopefully don't have to write more than 10 lines of code or so.

**Comment by LienDNguyen** [comment]
That sounds kinda complicated, but I'll try to do some of them over the weekend. Thanks!

**Comment by DanielSchuette** [comment]
It should be straight forward. If not, let me know!

**Comment by LienDNguyen** [comment]
I installed using anaconda prompt, and it said "successfully installed"

Next is the weird part, I have 2 environments available, one is base (root) which has python 2.7 and can't run the jupyter notebook I have, so I use the other one, anaconda3, which has python 3.

When I opened the notebook in the anaconda3 environment, I get the error message "No module named 'ca_img_analyzer'"

When I opened the notebook in the base environment (cos' that's where the package was installed to, I think), I got another error message: "No module named 'rof"

:(
Will try again soon.

**Comment by LienDNguyen** [comment]
Yep, the output was rof and 120. I can figure out how to install it to the other environment.

**Comment by LienDNguyen** [comment]
![1_khp3bjnqy4mc8gpfuz4r-q](https://user-images.githubusercontent.com/43080207/47595282-8ad93500-d94d-11e8-9f1f-aeb49bf6546f.jpeg)

I like this cartoon.

**Comment by DanielSchuette** [comment]
Cool! That means it works. You can use the same method to update the package since I will add more and more functionality to it I guess:

`(Anaconda prompt) python -m pip install --index-url https://test.pypi.org/simple/ ca_img_analyzer --upgrade`

(the `--upgrade` might not be necessary, I'm not 100% sure)
